apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-docker
  labels:
    app: spring-boot-docker
spec:
  replicas: 3
  template:
    metadata:
      name: spring-boot-docker
      labels:
        app: spring-boot-docker
    spec:
      containers:
        - name: spring-boot-docker
          image: sergeystol/spring-boot-docker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: spring-boot-docker
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-docker-service
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-docker
  ports:
    - port: 8080
